http://localhost:8080

-ks

Content-Type: application/json; charset=utf-8

--

--
GET /dt/type/mytype

--
POST /dt/type/mytype

{
  "attributes": ["four", "five", "six"]
}

--
GET /fitness

--
GET /observe

